# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

# Set the correct toolchain
- script: |
    rustup default stable
    rustup update stable
  displayName: "Set correct Rust version"

# Output rust environment
- script: |
    rustc --version
    cargo --version
    rustup --version
  displayName: Check installed rust version