[package]
name = "symbols"
version = "0.1.0"
authors = ["Matt Schulte <schultetwin1@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
clap = "2.32"
log = "0.4"
pretty_env_logger = "0.3"
ignore = "0.4"
rust-s3 = "0.26"
symbolic-debuginfo = "8.0"
hex = "0.4.0"
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
url = "2.2"
xdg = "2.2"