[package]
name = "symbols"
version = "0.1.0"
authors = ["Matt Schulte <schultetwin1@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
b2creds = "0.1"
clap = "2.32"
log = "0.4"
pretty_env_logger = "0.3"
ignore = "0.4"
rust-s3 = { version = "0.27.0-rc4", default-features = false, features = ["sync-rustls-tls"] }
symbolic-debuginfo = "8.0"
hex = "0.4.0"
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
url = "2.2"
directories = "3.0"
walkdir = "2"

[dependencies.rusqlite]
version = "0.24.2"
features = ["bundled"]