[package]
name = "dbg"
version = "0.1.0"
authors = ["Matt Schulte <schultetwin1@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.32"
log = "0.4"
pretty_env_logger = "0.3"
walkdir = "2"
goblin = "0.0.19"
pdb = "0.2.0"
reqwest = "0.9.9"