[package]
name = "symbols"
version = "0.2.0"
authors = ["Matt Schulte <schultetwin1@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
b2creds = "0.1"
clap = "2.32"
log = "0.4"
pretty_env_logger = "0.3"
ignore = "0.4"
rust-s3 = { version = "0.26.4", default-features = false, features = ["rustls-tls"] }
symbolic-debuginfo = "8.0"
tokio = { version = "0.2.0", features = ["full"] }
hex = "0.4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.5"
url = "2.2"
directories = "3.0"
walkdir = "2"
open = "1"
rand = "0.8"
reqwest = { version = "0.11", features = ["blocking", "json"] }
strum = { version = "0.22", features = ["derive"] }
keyring = "1"
rpassword = "7"
sha2 = "0.10"
data-encoding = "2.3"

[dependencies.rusqlite]
version = "0.24.2"
features = ["bundled"]